---
- name: install containerd
  apt:
    name: containerd

- name: create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: generate containerd config
  shell: |
    containerd config default | sudo tee config.toml
    sed -i "s#registry.k8s.io/pause#registry.aliyuncs.com/google_containers/pause#g" /etc/containerd/config.toml
  args:
    chdir: /etc/containerd
    creates: config.toml
  notify: restart containerd

- name: flush handlers
  meta: flush_handlers

- name: ensure containerd is running
  systemd:
    name: containerd
    state: started
    enabled: true
