---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: add hosts
  blockinfile:
    path: /etc/hosts
    block: |
      10.0.0.11 k8s-master
      10.0.0.31 k8s-node01
      10.0.0.41 k8s-node02
